# Generated by Django 3.2.5 on 2021-07-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
